name: Python Scheduled Script

on:
  schedule:
  - cron: "58 01 * * 0-6"
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Istanbul"
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repo to github runner
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      - name: Fetching the original data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git fetch origin main  # Fetch changes from the remote repository
          git reset --hard origin/main  # Reset the local repository to match the remote repository
      - name: Get data from data_pulling-transform-script
        env: 
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: | 
           python data_pull_transform.py
           python data_metrics.py
      - name: Commit data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "GH ACTION Data Update: $(date)"
          git push origin main
        env:
          REPO_KEY: ${{ secrets.GH_UPLOAD_TOKEN }}
          username: github-actions
      - name: Calculate metrics with data_metrics
        env: 
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: python data_metrics.py
      - name: Commit metrics
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "GH ACTION Metrics Update: $(date)"|
          git push origin main
        env:
          REPO_KEY: ${{ secrets.GH_UPLOAD_TOKEN }}
          username: github-actions
